### ISSUE TITLE
ApplicationServices is not available when building for iOS Simulator

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/buildozer#1547] opened 2023-01-16 16:13 UTC
I can't get the `buildozer ios debug` command to work correctly in any way.

**`Kivy-iOS` Installation Method**

```bash
python3 -m venv venv
. venv/bin/activate
pip3 install kivy-ios
```

![Снимок экрана 2023-01-16 в 14 29 39](https://user-images.githubusercontent.com/16930280/212668173-9c924f40-9547-4a09-bb45-8ff86953d1ed.png)

**Next step**

```bash
toolchain clean
toolchain distclean
toolchain build python3 openssl kivy==master
pip3 install buildozer
```
![Снимок экрана 2023-01-16 в 14 34 47](https://user-images.githubusercontent.com/16930280/212669509-dfa9097a-9504-4962-9a78-a35168499cb1.png)

```bash
export PATH="$PATH:/Users/macbookair/Opt/venv/bin"
```

![Снимок экрана 2023-01-16 в 14 38 46](https://user-images.githubusercontent.com/16930280/212669746-5848ea32-706a-442c-af97-0b9c59b160f9.png)

**Next step**

```bash
toolchain create MyApp /path/to/my/app
cd /path/to/my/app
buildozer ios debug
```

**Output**

```bash
[DEBUG   ] note: Using new build system
[DEBUG   ] note: Planning build
[DEBUG   ] note: Constructing build description
[DEBUG   ] warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Static Library' from project 'SDL_image')
[DEBUG   ] warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'Static Library' from project 'SDL_image')
[DEBUG   ] error: ApplicationServices is not available when building for iOS Simulator. (in target 'Static Library' from project 'SDL_image')
[DEBUG   ] 
[DEBUG   ] ** BUILD FAILED **

RAN: /usr/bin/xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks=4 ONLY_ACTIVE_ARCH=NO ARCHS=x86_64 BITCODE_GENERATION_MODE=bitcode HEADER_SEARCH_PATHS=/Users/macbookair/Projects/Dev/Freelance/fishingapp/.buildozer/ios/platform/kivy-ios/dist/include/common/sdl2 -sdk iphonesimulator -project Xcode/SDL_image.xcodeproj -target 'Static Library' -configuration Release
```

I am using the target version of `iPhone 12`:

![Снимок экрана 2023-01-16 в 19 02 47](https://user-images.githubusercontent.com/16930280/212721404-3410fcb9-fb31-480c-87b1-98512d9b3259.png)

**iOS specific**

ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0
ios.codesign.allowed = false

**Versions**

* Python : 3.9
* MacOS version : macOS Catalina 10.16.7

**Comment by misl6** [comment] 2023-01-21 10:17
Transferred the issue to `buildozer`, which will need a huge cleanup for the iOS part.

**Comment by misl6** [comment] 2023-01-21 10:19
> @misl6 Are there any instructions for configuring the `XCode` project to build a package for `iOS`? Because I'm sure it's all about my crooked hands :)

Most of the work is handled via the template, but if you need some help feel free to ping me on Discord, we may end up to write a how-to guide for other users 😀

**Comment by HeaTTheatR** [comment] 2023-01-21 10:37
@misl6 Yes, I haven't found a detailed practical guide on how to create an iOS package using a `Bulldozer`. Perhaps if I had a physical `iPhone` device, as shown in this video - https://www.youtube.com/watch?v=UAi3PG-qN2k - then there would be no problems. But I haven't tried to create such builds since I don't have an `iPhone` device.

**Comment by misl6** [comment] 2023-02-04 09:53
Duplicate of https://github.com/kivy/kivy-ios/issues/763  (XCode >= 13 is now a requirement)

**Closed by misl6** 2023-02-04 09:53 UTC
