### ISSUE TITLE
Kivy in pyCharm 

### ISSUE THREAD

**Issue by sundusabdullah** [kivy/buildozer#682] opened 2018-06-20 00:18 UTC
hello everyone 
I work on mac 10.13.5 and python 3.6 
there is a problem when installing kivy package in PyCharm
anyone have the idea how to solve this problem

![screen shot 1439-10-05 at 10 33 28 pm](https://user-images.githubusercontent.com/36115448/41630586-5fa968c0-7438-11e8-9ade-4a1ba7249edb.png)

**Comment by tshirtman** [comment] 2018-06-20 00:29
Looks like you want to install an older version of Cython.

pip install Cython==0.26

should do it.

Anyway, this is a support request, not a bug report, so i'll close it, if you need more help, please instead use the support channels (kivy-users google groups, or stackoverflow.com, or reddit.com/r/kivy, or kivy@freenode.net irc).

**Closed by tshirtman** 2018-06-20 00:29 UTC
