### ISSUE TITLE
orientation = portrait fails

### ISSUE THREAD

**Issue by jianni1** [kivy/buildozer#1546] opened 2023-01-16 06:53 UTC
### Versions
build environment 
* ubuntu 22.04.1
* pipenv latest
* buildozer latest
* p4a latest
* python 3.9.9

### Description
Write the "orientation = portrait" code in file buildozer.spec, but the screen will still reverse

**Comment by misl6** [comment] 2023-01-16 17:51
Duplicate of https://github.com/kivy/python-for-android/issues/2724

(I'm working on a PR that fixes it, but on the linked issue there's a workaround that could be used immediately)

**Closed by misl6** 2023-01-16 17:51 UTC
