### ISSUE TITLE
Cannot use numpy with buildozer

### ISSUE THREAD

**Issue by kunguz** [kivy/buildozer#232] opened 2015-09-15 14:06 UTC
Here is what happens when I try to use Numpy using buildozer:

    [39m[0m[36m# Check configuration tokens[39m[0m
    [39m[0m[36m# Ensure build layout[39m[0m
    [39m[0m[36m# Check configuration tokens[39m[0m
    [39m[0m[36m# Preparing build[39m[0m
    [39m[0m[36m# Check requirements for android[39m[0m
    [39m[0m[30m[1m# Run 'dpkg --version'[39m[0m
    [39m[0m[30m[1m# Cwd None[39m[0m
    Debian `dpkg' package management program version 1.17.25 (amd64).
    This is free software; see the GNU General Public License version 2 or
    later for copying conditions. There is NO warranty.
    [39m[0m[30m[1m# Search for Git (git)[39m[0m
    [39m[0m[30m[1m#  -> found at /usr/bin/git[39m[0m
    [39m[0m[30m[1m# Search for Cython (cython)[39m[0m
    [39m[0m[30m[1m#  -> found at /usr/bin/cython[39m[0m
    [39m[0m[30m[1m# Search for Java compiler (javac)[39m[0m
    [39m[0m[30m[1m#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac[39m[0m
    [39m[0m[30m[1m# Search for Java keytool (keytool)[39m[0m
    [39m[0m[30m[1m#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool[39m[0m
    [39m[0m[36m# Install platform[39m[0m
    [39m[0m[36m# Apache ANT found at /home/kaan/.buildozer/android/platform/apache-ant-1.9.4[39m[0m
    [39m[0m[36m# Android SDK found at /home/kaan/.buildozer/android/platform/android-sdk-21[39m[0m
    [39m[0m[36m# Android NDK found at /home/kaan/.buildozer/android/platform/android-ndk-r9c[39m[0m
    [39m[0m[36m# Check application requirements[39m[0m
    [39m[0m[30m[1m# Run './distribute.sh -l'[39m[0m
    [39m[0m[30m[1m# Cwd /home/kaan/demo/.buildozer/android/platform/python-for-android[39m[0m
    Available modules: android apsw audiostream bidi boost cherrypy c_igraph cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer freetype gevent greenlet harfbuzz hostpython igraph jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws wokkel zeroconf zope
    [39m[0m[30m[1m# Application requirements already installed, pass[39m[0m
    [39m[0m[36m# Check garden requirements[39m[0m
    [39m[0m[36m# Compile platform[39m[0m
    [39m[0m[30m[1m# Run './distribute.sh -l'[39m[0m
    [39m[0m[30m[1m# Cwd /home/kaan/demo/.buildozer/android/platform/python-for-android[39m[0m
    Available modules: android apsw audiostream bidi boost cherrypy c_igraph cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer freetype gevent greenlet harfbuzz hostpython igraph jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws wokkel zeroconf zope
    [39m[0m[30m[1m# Clean and build python-for-android[39m[0m
    [39m[0m[30m[1m# Remove directory and subdirectory /home/kaan/demo/.buildozer/android/platform/python-for-android/dist/Gazes[39m[0m
    [39m[0m[30m[1m# Run './distribute.sh -m "numpy pyjnius kivy" -d "Gazes"'[39m[0m
    [39m[0m[30m[1m# Cwd /home/kaan/demo/.buildozer/android/platform/python-for-android[39m[0m
    [34;01mCheck build dependencies for Ubuntu[39;49;00m
    [34;01mCheck environment[39;49;00m
    [30;01mSDK located at /home/kaan/.buildozer/android/platform/android-sdk-21[39;49;00m
    [30;01mNDK located at /home/kaan/.buildozer/android/platform/android-ndk-r9c[39;49;00m
    [30;01mNDK version is r9c[39;49;00m
    [30;01mAPI level set to 14[39;49;00m
    [34;01mCheck NDK location[39;49;00m
    [34;01mCheck mandatory tools[39;49;00m
    [34;01mDistribution will be located at /home/kaan/demo/.buildozer/android/platform/python-for-android/dist/Gazes[39;49;00m
    [34;01mEntering in ARM environment[39;49;00m
    [30;01mCompiler found at /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc[39;49;00m
    [30;01mPATH is /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/:/home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/:/home/kaan/.buildozer/android/platform/android-ndk-r9c:/home/kaan/.buildozer/android/platform/android-sdk-21/tools:/home/kaan/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin[39;49;00m
    [34;01mLeaving ARM environment[39;49;00m
    [30;01mRead numpy recipe[39;49;00m
    [30;01mModule numpy depend on python[39;49;00m
    [30;01mRead pyjnius recipe[39;49;00m
    [30;01mModule pyjnius depend on python sdl[39;49;00m
    [30;01mRead kivy recipe[39;49;00m
    [30;01mModule kivy depend on pygame pyjnius android[39;49;00m
    [30;01mRead python recipe[39;49;00m
    [30;01mModule python depend on hostpython[39;49;00m
    [30;01mIgnored python, already processed[39;49;00m
    [30;01mRead sdl recipe[39;49;00m
    [30;01mModule sdl depend on python[39;49;00m
    [30;01mRead pygame recipe[39;49;00m
    [30;01mModule pygame depend on python sdl[39;49;00m
    [30;01mIgnored pyjnius, already processed[39;49;00m
    [30;01mRead android recipe[39;49;00m
    [30;01mModule android depend on pygame[39;49;00m
    [30;01mRead hostpython recipe[39;49;00m
    [30;01mIgnored python, already processed[39;49;00m
    [30;01mIgnored python, already processed[39;49;00m
    [30;01mIgnored sdl, already processed[39;49;00m
    [30;01mIgnored pygame, already processed[39;49;00m
    [34;01mModules changed to hostpython python numpy sdl pygame pyjnius android kivy[39;49;00m
    [34;01mPure-Python modules changed to [39;49;00m
    [34;01mRun get packages[39;49;00m
    [30;01mDownload package for hostpython[39;49;00m
    [30;01mModule hostpython already downloaded[39;49;00m
    [30;01mDownload package for python[39;49;00m
    [30;01mModule python already downloaded[39;49;00m
    [30;01mDownload package for numpy[39;49;00m
    [30;01mModule numpy already downloaded[39;49;00m
    [30;01mDownload package for sdl[39;49;00m
    [30;01mNo package for sdl[39;49;00m
    [30;01mDownload package for pygame[39;49;00m
    [30;01mModule pygame already downloaded[39;49;00m
    [30;01mDownload package for pyjnius[39;49;00m
    [30;01mModule pyjnius already downloaded[39;49;00m
    [30;01mDownload package for android[39;49;00m
    [30;01mNo package for android[39;49;00m
    [30;01mDownload package for kivy[39;49;00m
    [30;01mModule kivy already downloaded[39;49;00m
    [34;01mRun prebuild[39;49;00m
    [30;01mCall prebuild_hostpython[39;49;00m
    [30;01mCall prebuild_python[39;49;00m
    [30;01mCall prebuild_numpy[39;49;00m
    [30;01mCall prebuild_sdl[39;49;00m
    [30;01mCall prebuild_pygame[39;49;00m
    [30;01mCall prebuild_pyjnius[39;49;00m
    [30;01mCall prebuild_android[39;49;00m
    [30;01mCall prebuild_kivy[39;49;00m
    [34;01mRun build[39;49;00m
    [30;01mSkipped build_hostpython[39;49;00m
    [30;01mSkipped build_python[39;49;00m
    [30;01mCall build_numpy[39;49;00m
    [34;01mEntering in ARM environment[39;49;00m
    [30;01mCompiler found at /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc[39;49;00m
    non-existing path in 'numpy/distutils': 'site.cfg'
    non-existing path in 'numpy/f2py': 'docs'
    non-existing path in 'numpy/f2py': 'f2py.1'
    F2PY Version 2
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_info:
      FOUND:
        libraries = ['openblas']
        library_dirs = ['/usr/lib']
        language = f77

      FOUND:
        libraries = ['openblas']
        library_dirs = ['/usr/lib']
        language = f77

    non-existing path in 'numpy/lib': 'benchmarks'
    lapack_opt_info:
    openblas_lapack_info:
    C compiler: cc

    creating /tmp/tmpd5glYu/tmp
    creating /tmp/tmpd5glYu/tmp/tmpd5glYu
    compile options: '-c'
    cc: /tmp/tmpd5glYu/source.c
    cc /tmp/tmpd5glYu/tmp/tmpd5glYu/source.o -L/usr/lib -lopenblas -o /tmp/tmpd5glYu/a.out
      FOUND:
        libraries = ['openblas']
        library_dirs = ['/usr/lib']
        language = f77

      FOUND:
        libraries = ['openblas']
        library_dirs = ['/usr/lib']
        language = f77

    running build_ext
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize LaheyFCompiler
    Could not locate executable lf95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    Could not locate executable fort
    customize IntelItaniumFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PathScaleFCompiler
    Could not locate executable pathf95
    don't know how to compile Fortran code on platform 'posix'
    C compiler: ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c'
    ccache: _configtest.c
    ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm _configtest.o -o _configtest
    success!
    removing: _configtest.c _configtest.o _configtest
    C compiler: ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c'
    ccache: _configtest.c
    _configtest.c:1:5: warning: conflicting types for built-in function 'exp' [enabled by default]
     int exp (void);
         ^
    ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm _configtest.o -o _configtest
    _configtest.o:_configtest.c:function main: error: undefined reference to 'exp'
    collect2: error: ld returned 1 exit status
    _configtest.o:_configtest.c:function main: error: undefined reference to 'exp'
    collect2: error: ld returned 1 exit status
    failure.
    removing: _configtest.c _configtest.o
    C compiler: ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c'
    ccache: _configtest.c
    _configtest.c:1:5: warning: conflicting types for built-in function 'exp' [enabled by default]
     int exp (void);
         ^
    ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm _configtest.o -lm -o _configtest
    success!
    removing: _configtest.c _configtest.o _configtest
    building library "npysort" sources
      adding 'build/src.linux-x86_64-2.7/numpy/core/src/private' to include_dirs.
    None - nothing done with h_files = ['build/src.linux-x86_64-2.7/numpy/core/src/private/npy_partition.h', 'build/src.linux-x86_64-2.7/numpy/core/src/private/npy_binsearch.h']
    building extension "numpy.core._dummy" sources
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h' to sources.
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h' to sources.
    executing numpy/core/code_generators/generate_numpy_api.py
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__multiarray_api.h' to sources.
    numpy.core - nothing done with h_files = ['build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__multiarray_api.h']
    building extension "numpy.core.multiarray" sources
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h' to sources.
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h' to sources.
    executing numpy/core/code_generators/generate_numpy_api.py
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__multiarray_api.h' to sources.
    numpy.core - nothing done with h_files = ['build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__multiarray_api.h']
    building extension "numpy.core.umath" sources
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h' to sources.
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h' to sources.
    executing numpy/core/code_generators/generate_ufunc_api.py
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__ufunc_api.h' to sources.
      adding 'build/src.linux-x86_64-2.7/numpy/core/src/umath' to include_dirs.
    numpy.core - nothing done with h_files = ['build/src.linux-x86_64-2.7/numpy/core/src/umath/funcs.inc', 'build/src.linux-x86_64-2.7/numpy/core/src/umath/simd.inc', 'build/src.linux-x86_64-2.7/numpy/core/src/umath/loops.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__ufunc_api.h']
    building extension "numpy.core.scalarmath" sources
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h' to sources.
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h' to sources.
    executing numpy/core/code_generators/generate_numpy_api.py
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__multiarray_api.h' to sources.
    executing numpy/core/code_generators/generate_ufunc_api.py
      adding 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__ufunc_api.h' to sources.
      adding 'build/src.linux-x86_64-2.7/numpy/core/src/private' to include_dirs.
    numpy.core - nothing done with h_files = ['build/src.linux-x86_64-2.7/numpy/core/src/private/scalarmathmodule.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/config.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/_numpyconfig.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__multiarray_api.h', 'build/src.linux-x86_64-2.7/numpy/core/include/numpy/__ufunc_api.h']
    building extension "numpy.core._dotblas" sources
      adding 'numpy/core/blasdot/_dotblas.c' to sources.
      adding 'numpy/core/blasdot/python_xerbla.c' to sources.
      adding 'numpy/core/blasdot/apple_sgemv_patch.c' to sources.
    building extension "numpy.core.umath_tests" sources
    building extension "numpy.core.test_rational" sources
    building extension "numpy.core.struct_ufunc_test" sources
    building extension "numpy.core.multiarray_tests" sources
    building extension "numpy.core.operand_flag_tests" sources
    building extension "numpy.lib._compiled_base" sources
    building extension "numpy.fft.fftpack_lite" sources
    building extension "numpy.linalg.lapack_lite" sources
      adding 'numpy/linalg/lapack_litemodule.c' to sources.
      adding 'numpy/linalg/lapack_lite/python_xerbla.c' to sources.
    building extension "numpy.linalg._umath_linalg" sources
      adding 'numpy/linalg/umath_linalg.c.src' to sources.
      adding 'numpy/linalg/lapack_lite/python_xerbla.c' to sources.
    building extension "numpy.random.mtrand" sources
    C compiler: ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c'
    ccache: _configtest.c
    ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm _configtest.o -o _configtest
    _configtest
    failure.
    removing: _configtest.c _configtest.o _configtest
    building data_files sources
    build_src: building npy-pkg config files
    running build_clib
    customize UnixCCompiler
    customize UnixCCompiler using build_clib
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    warning: build_ext: f77_compiler=None is not available.

    building 'numpy.core._dotblas' extension
    warning: build_ext: extension 'numpy.core._dotblas' has Fortran libraries but no Fortran linker found, using default linker

    compiling C sources
    C compiler: ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC

    compile options: '-DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/blasdot -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -c'
    ccache: numpy/core/blasdot/python_xerbla.c
    ccache: numpy/core/blasdot/_dotblas.c
    numpy/core/blasdot/_dotblas.c: In function 'dotblas_matrixproduct':
    numpy/core/blasdot/_dotblas.c:404:36: warning: passing argument 1 of 'PyUFunc_CheckOverride' from incompatible pointer type [enabled by default]
                                        &override, 2);
                                        ^
    In file included from numpy/core/blasdot/_dotblas.c:13:0:
    numpy/core/src/private/ufunc_override.h:167:1: note: expected 'struct PyUFuncObject *' but argument is of type 'struct PyObject *'
     PyUFunc_CheckOverride(PyUFuncObject *ufunc, char *method,
     ^
    ccache: numpy/core/blasdot/apple_sgemv_patch.c
    ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -shared -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/kaan/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/numpy/core/blasdot/_dotblas.o build/temp.linux-x86_64-2.7/numpy/core/blasdot/python_xerbla.o build/temp.linux-x86_64-2.7/numpy/core/blasdot/apple_sgemv_patch.o -L/usr/lib -L/home/kaan/demo/.buildozer/android/platform/python-for-android/build/python-install/lib -Lbuild/temp.linux-x86_64-2.7 -lopenblas -lpython2.7 -o build/lib.linux-x86_64-2.7/numpy/core/_dotblas.so
    /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/libopenblas.so while searching for openblas
    /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lopenblas
    collect2: error: ld returned 1 exit status
    /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/libopenblas.so while searching for openblas
    /home/kaan/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lopenblas
    collect2: error: ld returned 1 exit status
    [39m[0m[31m# Command failed: ./distribute.sh -m "numpy pyjnius kivy" -d "Gazes"[39m[0m
    [39m[0m[31m# [39m[0m
    [39m[0m[31m# Buildozer failed to execute the last command[39m[0m
    [39m[0m[31m# The error might be hidden in the log above this error[39m[0m
    [39m[0m[31m# Please read the full log, and search for it before[39m[0m
    [39m[0m[31m# raising an issue with buildozer itself.[39m[0m
    [39m[0m[31m# In case of a bug report, please add a full log with log_level = 2[39m[0m

**Comment by inclement** [comment] 2015-09-15 14:10
This is a duplicate of the p4a bug at https://github.com/kivy/python-for-android/issues/417

I have a fix for it in the revamp branch but haven't backported it yet.

**Closed by inclement** 2015-09-15 14:10 UTC
