### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by AriDeve** [kivy/buildozer#1504] opened 2022-09-04 19:18 UTC
### Versions

* Python: 3.10
* OS: Windows 10
* Buildozer: 1.4.0

### Description
`buildozer -v android debug` running into a problem with the gradle build, it throws errors and never completes. All the errors it throws are about memory, for examlple:
`.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/myapp/build/intermediates/merged_jni_libs/debug/out/arm64-v8a/libhidapi.so: Cannot allocate memory`

How would one solve this issue, as I haven't found a way to increase the allocated memory, and cannot think of any other solutions?

**Comment by RobertFlatt** [comment] 2022-10-14 06:24
It is possible this is related to WSL 1, upgrade to WSL 2

**Comment by Marcinosoft** [comment] 2022-11-04 03:51
I had similar 'Cannot allocate memory' issue.
 
	[DEBUG]:        > Task :mergeReleaseJniLibFolders FAILED
	[DEBUG]:        ERROR:Resource and asset merger: 1 exception was raised by workers:
	[DEBUG]:        A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$RunnableWrapperWorkAction
	[DEBUG]:
	[DEBUG]:            Cause 1: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$RunnableWrapperWork

	Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: ....../libs/armeabi-v7a/xxxxxxxxxxxxxxxxxx -> ...../xxxxxxxxxxxxxxxxxx: Cannot allocate memory

In xxxxxxxxxxxxxxxxxx there was one of following files, randomly:

	gdb.setup
	gdbserver
	libSDL2.so
	libSDL2_image.so
	libSDL2_mixer.so
	libSDL2_ttf.so
	libcrypto1.1.so
	libffi.so
	libhidapi.so
	libmain.so
	libpython3.9.so
	libsqlite3.so
	libssl1.1.so

I spend two days to figure out how to solve it, and in my case it was because of openjdk-17-jdk.
Buildozer 1.4.0 supports at least openjdk-11-jdk up to openjdk-17-jdk.
I installed openjdk-17-jdk as suggested here:
https://buildozer.readthedocs.io/en/latest/installation.html
or here:
https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst#android-on-ubuntu-2004-and-2204-64bit

	sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

I checked it with following environments with no success on two separate laptops:

	Windows 10 Pro 21H1, Buildozer 1.4.0, WSL v1 with Ubuntu 20.04, openjdk-17-jdk
	Windows 10 Pro 21H1, Buildozer 1.4.0, WSL v2 with Ubuntu 20.04, openjdk-17-jdk
	Windows 10 Pro 21H1, Buildozer 1.4.0, WSL v1 with Ubuntu 22.04, openjdk-17-jdk
	Windows 10 Pro 21H1, Buildozer 1.4.0, WSL v2 with Ubuntu 22.04, openjdk-17-jdk

I tried clean Ununtu installations, new Kivy projects, old projects which was previously working with Buildozer 1.2.0, removing .buildozer folder from project dir, upgrading gradle from 7.4.1 to 7.4.2, a lot of wasted time.

My build command was:

	buildozer -v android release

Strange, that from time to time I was able to build aab package, but never apk, setting following param of buildozer.spec:

	# (str) The format used to package the app for release mode (aab or apk or aar).
	android.release_artifact = apk

When this line was commented out aab file was able to build, but not always, sometimes 'Cannot allocate memory' also occured but not too often.

Then I started to thinking that this may happen because of Java 17. I wasn't able to uninstall it completely using:

	sudo apt remove openjdk-17-jdk
	sudo apt remove openjdk-17-jre
	sudo apt-get purge openjdk-17-jdk
	sudo apt-get purge openjdk-17-jre
	sudo apt-get --purge --autoremove openjdk-17-jdk
	sudo apt-get --purge --autoremove openjdk-17-jre

Java 17 was still present and it was default one in the path. I'm not an Ubuntu expert, I have no clue why Java 17 was still available.
I checked it using:

	java --version
and 17 was still available. Strange.

So I uninstalled Ubuntu, installed it again from Microsoft Store, set to WSL v1 using:

	wsl --set-default-version 1

then installed all Buildozer required components, but with Java 11 instead of 17, based on pages mentioned above:

	sudo apt install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
	pip3 install --user --upgrade Cython==0.29.19 virtualenv
	pip3 install --user --upgrade buildozer

And yes, now apk build process works like a charm.

Afterwards, I also faced with another build issue:

	[DEBUG]:        > Task :lintVitalRelease FAILED
	[DEBUG]:        /mnt/c/Kivy/my_project/.buildozer/android/platform/build-armeabi-v7a/dists/my_project/build.gradle:31: Error: Google Play requires that apps target API level 30 or higher.
	[DEBUG]:         [ExpiredTargetSdkVersion]
	[DEBUG]:                targetSdkVersion 27
	[DEBUG]:                ~~~~~~~~~~~~~~~~~~~
	[DEBUG]:
	[DEBUG]:           Explanation for issues of type "ExpiredTargetSdkVersion":

building with:

	buildozer -v android release

I solved it by following line change of buildozer.spec:

		# (int) Target Android API, should be as high as possible.
		android.api = 33

But it wasn't also easy, as long I realized that there is probably a Buildozer bug. Buildozer does not always update targetSdkVersion according to android.api param change.
Maybe I will register it as separate Buildozer issue. Till then here is my solution:
	
	https://stackoverflow.com/questions/72746288/buildozer-android-api-doesnt-change/74311692#74311692

So in my case it wasn't WSL version related issue. It worked same on v1 and v2. And it was not Ubuntu version related issue as well.
It was because of latest available Java 17 for Ubuntu. Maybe it's buggy, maybe this issue will be fixed in future releases of Java 17 or Gradle, but currently I recommend to downgrade to Java 11 and check if your problem will be solved.

**Comment by RobertFlatt** [comment] 2022-11-05 00:59
Thanks for the info on jdk17 and Gradle.

> But it wasn't also easy, as long I realized that there is probably a Buildozer bug. Buildozer does not always update targetSdkVersion according to android.api param change.

FYI https://github.com/Android-for-Python/Android-for-Python-Users#changing-buildozerspec

Also FYI https://github.com/Android-for-Python/Android-for-Python-Users#androidapi

**Comment by Marcinosoft** [comment] 2022-11-05 22:53
> FYI https://github.com/Android-for-Python/Android-for-Python-Users#changing-buildozerspec

Thanks. I wasn't aware of this. I was thinking that buildozer.spec is read and apply on every build. I changed other values in the past and it was always applied into apk. I never used buildozer appclean.
Really unclear sentence "_If buildozer.spec is changed the change probably won't propagate into the apk on the next build._"
"Probably"? what does it mean. It's kind a random behaviour, or maybe not every buildozer.spec param change will be applied on next build, that's why it's better to invoke it with appclean on every change.
In my opinion it would be better to include appclean functionality into buildozer -v android release and buildozer -v android debug by default to avoid suprises.

**Closed** 2022-11-12 09:52 UTC
Labels: support

**Comment by Marcinosoft** [comment] 2024-04-01 00:02
Just for update: this case is still valid for latest Kivy 2.3.0, Buildozer 1.5.0, and Ubuntu 20.04.6 and 22.04.3 running on WSL v1 and v2.
In short: switching OpenJDK from 17 to 11 makes Gradle successfull apk builds.

Install OpenJDK 11 on Ubuntu by running:
`sudo apt install -y openjdk-11-jdk`

Make OpenJDK 11 as default Java by running:
`sudo update-alternatives --config java`
and make selection of:
`/usr/lib/jvm/java-11-openjdk-amd64/bin/java`

**Comment by RobertFlatt** [comment] 2024-04-01 05:00
FYI I do not see the same issue - I don't know why my experience is different. 

How much _physical_ memory does the computer have?
Does the issue occur building 'Hello World'?
Does the issue occur building an app that has user specified Java code or packages?

Because you use an old Windows version, I'd wonder if you are using old hardware with insufficient physical memory for this task. So I'd look at the WSL process memory (see below), the default is going to depend on the Windows physical memory. It is possible to change the WSL process memory (see below) but if there is insufficient physical memory this won't help. Similarly for the Java heap size.

I'm not involved with development here, just a user driving by.

I use:

Windows 11
WSL2 
JDK 17
Buildozer 1.5 with default p4a

My .wslconfig is not the default for reasons unrelated to Buildozer/p4a .
```
C:\Users\Bobf>type .wslconfig
[wsl2]
memory=20GB
swap=16GB
```
My Ubuntu meminfo starts with
```
~>cat /proc/meminfo
MemTotal:       20485364 kB
MemFree:        18588696 kB
MemAvailable:   19072376 kB
```

**Comment by Marcinosoft** [comment] 2024-04-01 10:06
Hi @RobertFlatt.
Thanks for your response. I'm using Win10 Pro 22H2 x64 with 16GB RAM with Ubuntu 22.04.3 WSL v1 because Android emulators like Nox or Bluestacks are not compatible with WSL v2.
BTW. what kind of Android emulator are you using to test Kivy apps on Android? I'm using Nox (https://www.bignox.com/).

My second PC have got same Windows and 8GB RAM. I verified memory usage both on Windows and Ubuntu using top command during Buildozer build and seems there is no insufficient memory issue at all.
I tested it on Ubuntu 20.04.6 too, switched from WSL v1 to WSL v2, nothing helps.

What exact Ubuntu you are using? Can you share your:
wsl --status
wsl --version
output?

Can you check you OpenJDK version under Ubuntu?
java --version

I will try on my third PC which is running Windows 11. I'm testing on very simple "hello world" Kivy app, just created, I reinstalled Ubuntu several times, so it's clean. I also tried to downgrade Buildozer to 1.4.0, it doesn't help, seems this is not Buildozer related issue. It's something related to Gradle and JDK 17 on WSL. Same happens with gradle 7.4.1 which was used by previous python-for-android before this commit https://github.com/kivy/python-for-android/pull/2887, and current Gradle 8.0.2, which is no longer compatible with JDK 11, but I requested to downgrade it to latest 7.x here https://github.com/kivy/python-for-android/issues/3000.

I also tried to specify and increase heap size for Gradle within gradlew shell script located within project's .buildozer\android\platform\build-armeabi-v7a\dists\poject_name\ folder - nothing works, still Cannot allocate memory executing file copy in Gradle mergeReleaseJniLibFolders task. It happens usually for libffi.so or libssl1.1.so.
There is plenty of free disk space, free RAM. Same issue on two separate desktops, it's really annoying. I spend hours again to find root cause or any other workaround except downgrading JDK to 11, and nothing.
Also I've tried to copy my project to Linux partition, it's same when project is placed on Windows partition.
Switching default java from 17 to 11 solves this issue immediately. Gradle can build apk successfully all the time. After switching to 17 - it always fail on mergeReleaseJniLibFolders task.

I found similar issues related to WSL and Flutter. It's related to something called dart which probably is not used by Kivy/Buildozer/p4a:

https://stackoverflow.com/questions/64268257/flutter-build-fails-on-wsl2-with-filesystemexception-os-error-cannot-allocate
https://gist.github.com/swift-kim/0e6dcf1cdd36eaf0453a8eec2775287d
https://github.com/dart-lang/sdk/issues/46749

Knowing that there is at least one person ib the world, who is able to build Kivy apk on WSL, I mean you :) I will try to reinstall Ubuntu using WSL v2 on Windows 11, then create fresh new, simple project base on Kivy 2.3.0, Buildozer 1.5.0 with JDK 17, then will share results with you.

**Comment by RobertFlatt** [comment] 2024-04-02 01:25
WSL2 is a common platform for Buildozer users.

WSL1 has had issues, for example https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#c-compiler-cannot-create-executables  and https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#usrbingzip-1-elf--not-found  Don't use WSL1.

Do not build on the Windows file system. This may give unpredictable results with some Python packages, and builds that are five to ten times slower than on the Linux partition. https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#install

Don't waste your time on the Windows machine with 8GB of physical memory, my guess, there is probably not enough memory left for Gradle on WSL.

Yes Gradle appears to use more memory with Java 17 (unknown by me if this is due to change in Gradle or Java). This is usually only a problem with apps that are too big for the Android Store, Hello World is NOT an example of "too big".  https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#javalangoutofmemoryerror . See comments there about adjusting heap size. Note the comment about rebooting, Gradle can leak heap memory when it fails outofmemory - causing following builds to fail with the same symptom but a potentially incorrectly. 

Gradle is a tool supplied with the Android build tools, so any tool set that builds for Android potentially shows this issue. Since Gradle is somebody else's software and mostly 'just works' I don't expect you'll find a lot of detailed knowledge here. Best guess this issue is something site specific. 

I don't use an emulator, you could use the emulator in Android Studio on Windows https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#appendix-b--using-an-emulator

I don't think the issue is fine tuning versions, but in answer to your question.

```
C:\Users\Bobf>wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2
```
```
C:\Users\Bobf>wsl --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3374

```
```
~>java --version
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

As I said previously
> I don't know why my experience is different.

So I don't have any suggestions for you, except heap size, which by default depends on process memory size, which by default depends on physical memory. 

I'd also check for package interaction, try
```
~/>apt list --installed | grep jdk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

openjdk-17-jdk-headless/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed,automatic]
openjdk-17-jdk/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed]
openjdk-17-jre-headless/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed,automatic]
openjdk-17-jre/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed,automatic]
```
(I've no idea why that repeats itself).

As I said earlier I'm driving by, I've got my own journey, so now moving on. Good luck in your quest.

**Comment by Marcinosoft** [comment] 2024-04-02 21:37
> WSL1 has had issues, for example https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#c-compiler-cannot-create-executables and https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#usrbingzip-1-elf--not-found Don't use WSL1.
> 
> Do not build on the Windows file system. This may give unpredictable results with some Python packages, and builds that are five to ten times slower than on the Linux partition. https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#install
> 
> Don't waste your time on the Windows machine with 8GB of physical memory, my guess, there is probably not enough memory left for Gradle on WSL.

I cannot fully agree. There are pros and cons, and in my opinion there are more pros over cons regarding WSL v1.

Issue no1 https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#c-compiler-cannot-create-executables
is really easy to fix, which I described here:
https://github.com/kivy/buildozer/issues/1543#issuecomment-1382574110
Fix have to applied only once at first Buildozer run. It's marked as (EXPERTS ONLY) but in fact it's a piece of cake.
I never heard or faced issue no2 https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#usrbingzip-1-elf--not-found.

I was building three Kivy projects last three years with group of five childrens using Kivy 2.0.0, then 2.1.0. All had their own laptops running Windows 10 or 11. We were learning Python and Kivy. All were using Python 3.8, PyCharm CE, Ubuntu 18, 20 or 22 with WSL v1 and Nox as Android Emulator for debugging and testing. Some setups were equipped with 8GB RAM and everything was working. It was painfull at some moments, there were challenges because of different Windows security setups, different antivirus software, access rights, human mistakes, remote learning and so on, but finally Kivy was able to build with success for each of them.

WSL v1 was choosen because of severs meaningful pros, which are described here:
https://learn.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2

1. Filesystem operations on mounted devices are faster using WSL v1 compared to v2, that's make building projects located on Windows partition easier. Just go to Ubuntu terminal within PyCharm, type
`buildozer -v android release` and that's all. apk is placed withing project's folder located on Windows. I/O is faster in this case using WSL v1.

2. USB devices are fully supported by WSL v1, physical and virtual. It makes extremally ease to send apk using adb to real device attached to PC or virtual one which was Nox Android emulator in our case. Of course nobody used adb command. Just run `buildozer -v android release deploy` and here you go. It is automatically installed on Nox or any real phone or tablet connected to PC via USB cable. No need to additional setup, except turning usb debugging on real devices only. For Nox it's working out of the box. Moreover, wanna start your app and see console output from app running on Android? No problem, just run `buildozer -v android debug deploy run logcat` to build, then install app on Nox or real device, and see all messages within PyCharm console window. It was really helpfull searching why Kivy app is running fine under Windows, but cannot be started at all on Android. As far as I know there is no, or at least no simple, ability to communicate with USB devices between WSL v2 and Windows.

3. I believe that Linux running on WSL v1 can allocate as much memory as available in Windows. Both Linux and Windows seems to share same memory, so there is no strict memory allocation for VM like using WSL v2. It's good for PC with smaller amount of RAM.

We were using PCs with 8GB of RAM running PyCharm, Ubuntu on WSL v1 and Nox at the same time, with successfull Buildozer builds, really.

> Yes Gradle appears to use more memory with Java 17 (unknown by me if this is due to change in Gradle or Java). This is usually only a problem with apps that are too big for the Android Store, Hello World is NOT an example of "too big". https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#javalangoutofmemoryerror . See comments there about adjusting heap size. Note the comment about rebooting, Gradle can leak heap memory when it fails outofmemory - causing following builds to fail with the same symptom but a potentially incorrectly.

Gradle doesn't throw java.lang.OutOfMemoryError in my case. There is no java crash report, it looks different. At first sight I was thinking it is related to write permissions or too long path, but it's not. I can write, copy to same path where Gradle is trying to copy so files, but somehow Gradle can't, failing on random so file. Also knowing that java.nio.file.FileSystemException throws an `Cannot allocate memory` exception it doesn't sounds like general Java OOM exception. In fact may be related to WSL v1, but why same Gradle running on Java 11 can, but just switching Java to 17 cannot, really strange. Same Ubuntu, same Gradle (7.x), same project... I cannot undestand it.

> Gradle is a tool supplied with Google's Android build tools, so any tool set that builds for Android devices potentially shows this issue. Since Gradle is somebody else's software and mostly 'just works' I don't expect you'll find a lot of detailed knowledge here. Best guess this issue is something site specific.

Yeap, It's hard nut to crack, but I won't give up without a fight :)

> I don't use an emulator, you could use the emulator in Android Studio on Windows https://github.com/Android-for-Python/Android-for-Python-Users?tab=readme-ov-file#appendix-b--using-an-emulator

I heard about it, but when I was searching for something that childrens can handle, relatively small, easy to use, with similar look and feel like real Android device, I decided to use Nox.
In fact I never tried Android Studio's emulator. Also I'm not sure if it supports apk build for ARM arch, which can be easily run on Nox or real ARM device. Right now Buildozer supports building for multiple archs at same time but unfortunatelly it takes additional time.

> I don't think the issue is fine tuning versions, but in answer to your question.
> 
> ```
> C:\Users\Bobf>wsl --status
> Default Distribution: Ubuntu-22.04
> Default Version: 2
> ```
> 
> ```
> C:\Users\Bobf>wsl --version
> WSL version: 2.1.5.0
> Kernel version: 5.15.146.1-2
> WSLg version: 1.0.60
> MSRDC version: 1.2.5105
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.3374
> ```
> 
> ```
> ~>java --version
> openjdk 17.0.8.1 2023-08-24
> OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
> OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)
> ```

Thanks. I'm currently installing same setup on my laptop running on Win 11.

> As I said previously
> 
> > I don't know why my experience is different.
> 
> So I don't have any suggestions for you, except heap size, which by default depends on process memory size, which by default depends on physical memory.
> 
> I'd also check for package interaction, try
> 
> ```
> ~/>apt list --installed | grep jdk
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> openjdk-17-jdk-headless/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed,automatic]
> openjdk-17-jdk/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed]
> openjdk-17-jre-headless/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed,automatic]
> openjdk-17-jre/jammy-updates,jammy-security,now 17.0.8.1+1~us1-0ubuntu1~22.04 amd64 [installed,automatic]
> ```
> 
> (I've no idea why that repeats itself).

It's not repeating. First two rows are for JDK, rest are for JRE :)

> As I said earlier I'm driving by, I've got my own journey, so now moving on. Good luck in your quest.

Many thanks for huge piece of knowledge. I'll try to find solution for WSL v1.
It's still a good choice for Kivy apk building and testing.
I'll share my results, it may be helpful for others like me, who like swimming against the current ;)


Update: I've just build apk using my laptop running Windows 11, Ubuntu 22.04 (WSL v2), Kivy 2.3.0 and JDK 17. Laptop is equipped with 8GB RAM, while Ubuntu had 4GB total memory. Project was located on Windows partition and first build was very time consuming, but I don't know if it was because of WSL v2 slow I/O for mounted Windows partition or maybe because this hardware is just slower compared to my desktop setup running Windows 10. Maybe I will retry it with WSL v1 on same laptop to see difference between firts building same project located on Windows partition, on same hardware with WSL v1 and v2.
