### ISSUE TITLE
Bump default min SDK to 13: Fix crash on orientation change bug

### ISSUE THREAD

**Issue by miohtama** [kivy/buildozer#302] opened 2016-03-13 04:48 UTC
Currently min SDK is 9. Applications deployed with the default settings crash on orientation change. Please see:

https://github.com/kivy/python-for-android/issues/148#issuecomment-195872448

Min SDK 13 fixes the issue.

It would be better development experience to deploy with non-crashing defaults, though not sure about device market shares and such.

**Comment by dessant** [comment] 2016-05-05 16:54
Duplicate of https://github.com/kivy/buildozer/issues/264.

**Closed by dessant** 2016-05-05 16:54 UTC
