### ISSUE TITLE
New android target is unable to produce a python 4 android service

### ISSUE THREAD

**Issue by jtoledo1974** [kivy/buildozer#543] opened 2017-08-19 13:48 UTC
As described in https://github.com/tshirtman/kivy_service_osc/issues/1,  it is only possible to have a service with the android_old target

**Comment by inclement** [comment] 2017-08-19 14:14
Thanks for the report. This is a bug, but the new-style services (which are generally better anyway) should currently be working, see http://python-for-android.readthedocs.io/en/latest/services/#arbitrary-service-scripts.

I'll close this issue as a duplicate of https://github.com/kivy/python-for-android/issues/1049.

**Closed by inclement** 2017-08-19 14:14 UTC
