### ISSUE TITLE
buildozer debug is not running  this error is showing 

### ISSUE THREAD

**Issue by AnkitMArtin** [kivy/buildozer#622] opened 2018-02-17 11:45 UTC
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\buildozer-script.py", line 11, in <module>
    load_entry_point('buildozer', 'console_scripts', 'buildozer')()
  File "c:\users\ankit\buildozer\buildozer\scripts\client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "c:\users\ankit\buildozer\buildozer\__init__.py", line 122, in __init__
    self.config.read(filename)
  File "c:\program files\python36\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "c:\program files\python36\lib\configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'buildozer.spec', line: 1
'ï»¿[app]\n'

**Comment by hackalog** [comment] 2019-01-11 17:30
Looks like garbage (unicode character?) in the first line of your buildozer.spec file

**Comment by tanakanc** [comment] 2019-01-11 17:37
but in the file.spec 
the first line showed [app]

I tried change something in it such as [myapp] or test[app]



the error showed in the same way with new texts like
'ï»¿[myapp]\n'
'ï»¿test [app]\n'

**Comment by hackalog** [comment] 2019-01-11 17:44
It's a unicode encoding issue. Whatever editor you are using is adding a Byte Order Mark.

https://stackoverflow.com/questions/3255993/how-do-i-remove-%C3%AF-from-the-beginning-of-a-file

suggested workaround: use a different editor, or fix the encoding issues within whatever you are using.

**Comment by tanakanc** [comment] 2019-01-12 06:07
Thank you very much. it is helpful

**Comment by tanakanc** [comment] 2019-01-12 13:04
Finally, even though this problem was solved, but the root cause of my problem is that buildozer cannot run on window TT

**Comment by hackalog** [comment] 2019-01-12 17:17
@tanakanc can you close this issue?

**Comment by JonasT** [comment] 2019-01-12 17:33
it's fine @tanakanc you can't, @AnkitMArtin needs to close it (or one of the maintainers)

**Comment by hackalog** [comment] 2019-01-12 17:46
Whoop. My bad. Sorry for the noise!

**Closed** 2019-01-13 18:07 UTC
