### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/Users/gauravgupta/kivy/.buildozer/android/platform/build/dists/myellipse/build/outputs/apk/myellipse-debug.apk'

### ISSUE THREAD

**Issue by gauravgupta11** [kivy/buildozer#613] opened 2018-01-02 06:07 UTC
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33', 'console_scripts', 'buildozer')()
  File "/Library/Python/2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 103, in cmd_debug
    self.buildozer.build()
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/Library/Python/2.7/site-packages/buildozer/targets/android.py", line 808, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/gauravgupta/kivy/.buildozer/android/platform/build/dists/myellipse/build/outputs/apk/myellipse-debug.apk'

**Comment by colstew** [comment] 2018-01-12 21:16
I've come across this error too. The fix mentioned in issue #312 worked for me.

**Comment by cdyangbo** [comment] 2018-01-13 14:50
the problem is : in toolchain.py has two build_type ,gradle(build_tools_version>25.0 and exist gradlew)  otherwise ant. but in android.py, only jude exist gradlew but the default build_tools_version is 19.1.
Fix it: /usr/local/lib/python2.7/dist-packages/buildozer/tagets/android.py,:
       (1) at file top insert : `from distutils.version import LooseVersion`
       (2)  line 786 replace with below code:
       ```python
       # XXX found how the apk name is really built from the title
	__sdk_dir = self.android_sdk_dir
	build_tools_versions = os.listdir(join(__sdk_dir, 'build-tools'))
        build_tools_versions = sorted(build_tools_versions, key=LooseVersion)
        build_tools_version = build_tools_versions[-1]	
        gradle_files = ["build.gradle", "gradle", "gradlew"]
        is_gradle_build = any((exists(join(dist_dir, x)) for x in gradle_files)) and build_tools_version >= '25.0'
        ```
        @cdyangbo

**Comment by cdyangbo** [comment] 2018-01-13 15:01
same issue #312, i have fix it.

**Comment by ImtiyazKhan117** [comment] 2018-07-01 05:12
@cdyangbo
I can't edite the android.py file

**Comment by AndreMiras** [comment] 2018-07-04 13:11
Hi guys, can you give it a try on this PR https://github.com/kivy/buildozer/pull/691 and say if it fixes it for you?

**Comment by ImtiyazKhan117** [comment] 2018-07-08 17:57
@AndreMiras  thanks its for me.. but now i am dealing with another problem apk is not working on just screen pops and gone

**Comment by AndreMiras** [comment] 2018-07-09 09:08
Not sure if it's a related issue, but please share the adb (filtered) log with the relevant part.

**Comment by inclement** [comment] 2019-02-01 18:59
Closing as fixed.

**Closed by inclement** 2019-02-01 18:59 UTC
