### ISSUE TITLE
kivy app  built with buildozer, crashing on android .../site-packages/charset_normalizer/md.so" is for EM_X86_64 (62) instead of EM_AARCH64 

### ISSUE THREAD

**Issue by snowgato** [kivy/buildozer#1569] opened 2023-02-21 17:48 UTC
### Versions

* Python: 3.8.10
* OS: Ubuntu 20.0.4 on WSL2 ( WIndows 11 )
* Buildozer: 1.5.0 ( from pypi, pip install buildozer )
* Kivy is 2.1.0 from pip install kivy
### Description
The app should display repeatedly some stock quotes using Kivy and yahooquery module. It works on windows.
Buildozer build process produces an apk. When launched on the smartphone, the app window doesn't show up. adb logs report the following error:

02-21 18:02:40.903 12625 12674 I python  :   File "/home/ced/programmation/python/kivy/kivy_bourse/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/Bourse/arm64-v8a/charset_normalizer/cd.py", line 9, in <module>
02-21 18:02:40.903 12625 12674 I python  : ImportError: dlopen failed: "/data/data/ced.bart.bourse/files/app/_python_bundle/site-packages/charset_normalizer/md.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
02-21 18:02:40.903 12625 12674 I python  : Python for android ended.

### buildozer.spec
Command:
```sh

Buildozer command: buildozer -v android debug

Spec file:
```
Buildozer.spec:
[app]
title = Bourse
package.name = Bourse
package.domain = ced.bart
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json,wav
version = 0.1
requirements=python3,kivy==2.1.0,datetime,yahooquery,pandas,lxml,numpy,python-dateutil,six,pytz,requests-futures,requests,certifi,charset-normalizer,idna,urllib3,tqdm
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.1.0
fullscreen = 0
android.archs = arm64-v8a, armeabi-v7a
android.allow_backup = True
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0
ios.codesign.allowed = false
[buildozer]
log_level = 2
warn_on_root = 1

### Logs
[DEBUG]:        BUILD SUCCESSFUL in 23s
[DEBUG]:        31 actionable tasks: 30 executed, 1 up-to-date

[INFO]:    <- directory context /home/ced/programmation/python/kivy/kivy_bourse/.buildozer/android/platform/python-for-android
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:         Bourse: min API 21, includes recipes (hostpython3, libbz2, libffi, liblzma, librt, libxml2, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, libxslt, python3, sdl2, pytz, setuptools, cython, lxml, six, numpy, pyjnius, android, kivy, pandas, tqdm, requests, urllib3, datetime, charset-normalizer, certifi, requests-futures, yahooquery, python-dateutil, idna), built for archs (armeabi-v7a, arm64-v8a)
[INFO]:    Bourse has compatible recipes, using this one
[INFO]:    # Copying android package to current directory
[INFO]:    # Android package filename not found in build output. Guessing...
[INFO]:    # Found android package file: /home/ced/programmation/python/kivy/kivy_bourse/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/Bourse/build/outputs/apk/debug/Bourse-debug.apk
[INFO]:    # Add version number to android package
[INFO]:    # Android package renamed to Bourse-debug-0.1.apk
[DEBUG]:   -> running cp /home/ced/programmation/python/kivy/kivy_bourse/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/Bourse/build/outputs/apk/debug/Bourse-debug.apk Bourse-debug-0.1.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Android packaging done!
# APK Bourse-0.1-arm64-v8a_armeabi-v7a-debug.apk available in the bin directory

I download and install the apk on the xiaomi smartphone.
Then launching the app and
 using adb logcat -s python, I get the following message:

...
02-21 18:02:40.903 12625 12674 I python  :   File "/home/ced/programmation/python/kivy/kivy_bourse/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/Bourse/arm64-v8a/charset_normalizer/cd.py", line 9, in <module>
02-21 18:02:40.903 12625 12674 I python  : ImportError: dlopen failed: "/data/data/ced.bart.bourse/files/app/_python_bundle/site-packages/charset_normalizer/md.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
02-21 18:02:40.903 12625 12674 I python  : Python for android ended.

Thanks for your help !

**Comment by misl6** [comment] 2023-02-21 19:34
Duplicate of https://github.com/kivy/python-for-android/issues/2755

**Closed by misl6** 2023-02-21 19:34 UTC
