### ISSUE TITLE
openssl not available for download

### ISSUE THREAD

**Issue by Tyrn** [kivy/buildozer#1047] opened 2020-04-01 15:17 UTC
Today on creating a new project, failed to download openssl:
```
[INFO]:    Downloading openssl from https://www.openssl.org/source/openssl-1.1.1.tar.gz
Traceback (most recent call last):
...
ValueError: read of closed file
```
As of 2020-03-31 openssl-1.1.1.tar.gz is uploaded no longer:
[Downloads](https://www.openssl.org/source/) (it's openssl-1.1.1f.tar.gz now)

Where am I supposed to change the file name?

**Comment by bellorini** [comment] 2020-04-01 17:23
Hello, I had the same issue today.

Do not recommend doing what I did, because i`m a newbie and I do not know the consequences, but:
change the line 50 of the file at your local dir 
.buildozer/android/platform/python-for-android/pythonforandroid/recipes/openssl/__init__.py 

`50.  url_version = '1.1.1f' # <- here, add the *f*`

I hope it helps temporarily.

**Comment by misl6** [comment] 2020-04-01 17:55
It's more a `python-for-android` issue, but:
`https://www.openssl.org/source/openssl-1.1.1.tar.gz` is working for me.

Cam you confirm that and close the issue if it's fixed?

**Comment by AndreMiras** [comment] 2020-04-01 18:04
I could reproduce just now:
```
$ wget https://www.openssl.org/source/openssl-1.1.1.tar.gz
--2020-04-01 20:03:23--  https://www.openssl.org/source/openssl-1.1.1.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.openssl.org (www.openssl.org)... 95.100.127.91, 2a02:26f0:e0:5b7::c1e, 2a02:26f0:e0:595::c1e
Connecting to www.openssl.org (www.openssl.org)|95.100.127.91|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-01 20:03:23 ERROR 404: Not Found.

⌂68% θ79° [andre:~/workspace/EtherollApp] develop+* 8 ± wget https://www.openssl.org/source/openssl-1.1.1f.tar.gz
--2020-04-01 20:03:29--  https://www.openssl.org/source/openssl-1.1.1f.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.openssl.org (www.openssl.org)... 95.100.127.91, 2a02:26f0:e0:5b7::c1e, 2a02:26f0:e0:595::c1e
Connecting to www.openssl.org (www.openssl.org)|95.100.127.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9792828 (9.3M) [application/x-gzip]
Saving to: ‘openssl-1.1.1f.tar.gz’

openssl-1.1.1f.tar.gz                                       100%[==========================================================================================================================================>]   9.34M  4.13MB/s    in 2.3s    

2020-04-01 20:03:32 (4.13 MB/s) - ‘openssl-1.1.1f.tar.gz’ saved [9792828/9792828]
$
```
But not in my buildozer build :thinking: 
Anyway here's a PR https://github.com/kivy/python-for-android/pull/2117

**Comment by misl6** [comment] 2020-04-01 18:15
Yeah, probably there's a load balancer and an endpoint is having difficulties:
As you can see, I'm downloading from a different endpoint. :smile: 
```
--2020-04-01 20:10:52--  https://www.openssl.org/source/openssl-1.1.1.tar.gz
Resolving www.openssl.org (www.openssl.org)... 104.83.84.113, 2a02:26f0:128:39c::c1e, 2a02:26f0:128:38f::c1e
Connecting to www.openssl.org (www.openssl.org)|104.83.84.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8337920 (8,0M) [application/x-gzip]
Saving to: ‘openssl-1.1.1.tar.gz’

openssl-1.1.1.tar.gz                                  11%[============>                                                                                                         ] 937,02K  1,12MB/s 
```

**Comment by AndreMiras** [comment] 2020-04-01 18:22
Yes definitely seems to be it

**Comment by thica** [comment] 2020-04-05 20:39
Hi, they just changed he open ssl version to "f" and changed the location for the 1.1.1. So if it works for you, you might get the file from a cache!

**Comment by AndreMiras** [comment] 2020-05-30 08:57
I think the issue is gone, and was also related with a temporary hiccup of the provider. Feel free to reopen to discuss it further otherwise

**Closed by AndreMiras** 2020-05-30 08:57 UTC
