### ISSUE TITLE
scipy/_lib/_ccallback_c.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by MatBonv** [kivy/buildozer#880] opened 2019-04-15 17:17 UTC
### Versions

* Python: 3.7
* OS: Ubuntu VM

### Description

My app needs scipy but a part of scipy is 64 bit instead of 32 bit. The app crashes immediately on my phone.  Can this be fixed? Thanks in advance.

Command:
```sh
buildozer android deploy run logcat
```

### Logs

```
04-15 18:51:03.674 27504 27533 I python  : [INFO   ] [Factory     ] 184 symbols loaded
04-15 18:51:04.454 27504 27533 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
04-15 18:51:04.874 27504 27533 I python  :  Traceback (most recent call last):
04-15 18:51:04.874 27504 27533 I python  :    File "/home/kivy/Desktop/arduino_test/.buildozer/android/app/main.py", line 6, in <module>
04-15 18:51:04.874 27504 27533 I python  :    File "/home/kivy/Desktop/arduino_test/.buildozer/android/platform/build/build/python-installs/birdrec/scipy/__init__.py", line 119, in <module>
04-15 18:51:04.874 27504 27533 I python  :    File "/home/kivy/Desktop/arduino_test/.buildozer/android/platform/build/build/python-installs/birdrec/scipy/_lib/_ccallback.py", line 1, in <module>
04-15 18:51:04.874 27504 27533 I python  :  ImportError: dlopen failed: "/data/data/org.test.birdrec/files/app/_python_bundle/site-packages/scipy/_lib/_ccallback_c.so" is 64-bit instead of 32-bit
04-15 18:51:04.874 27504 27533 I python  : Python for android ended.
```

**Comment by AndreMiras** [comment] 2019-04-16 09:17
This is probably because `scipy` needs a recipe, so you can follow the guide and try to create one.
https://python-for-android.readthedocs.io/en/latest/

**Comment by podraco** [comment] 2019-10-07 10:27
might be a duplicate of this issue https://github.com/kivy/buildozer/issues/869

**Comment by Julian-O** [comment] 2023-10-25 02:36
This is out of scope here - it is a python-for-android issue.

It appears to have been addressed [here](https://github.com/kivy/python-for-android/pull/2370)

**Closed by Julian-O** 2023-10-25 02:36 UTC
